import { FormEvent, useEffect, useState } from 'react'
import { Ban, CheckCircle2, KeyRound, LoaderCircle, Play, PlugZap, Plus, Power, RefreshCw, Server, Trash2, XCircle } from 'lucide-react'
import { api } from '../lib/api'
import { toast } from '../lib/toast'
import type { McpServer } from '../types'
import { translateStatus, translateVisibility, useI18n } from '../i18n'

type Connection = {ok:boolean;message:string;protocol_version?:string;tools:Array<Record<string,unknown>>}

export function McpServersPage(){
  const {t}=useI18n()
  const [servers,setServers]=useState<McpServer[]>([])
  const [creating,setCreating]=useState(false)
  const [transport,setTransport]=useState<'streamable-http'|'stdio'>('streamable-http')
  const [busy,setBusy]=useState<string|null>(null)
  const [error,setError]=useState('')
  const load=()=>api<McpServer[]>('/mcp-servers').then(setServers)
  useEffect(()=>{load().catch(()=>undefined);const timer=window.setInterval(()=>load().catch(()=>undefined),5000);return()=>window.clearInterval(timer)},[])
  async function connect(server:McpServer){setBusy(server.id);setError('');try{const result=await api<Connection>(`/mcp-servers/${server.id}/connect`,{method:'POST'});toast(t('mcp.connected',{name:server.name,count:result.tools.length}),'success',{kind:'mcp.server.connected',resource_type:'mcp_server',resource_id:server.id});await load()}catch(reason){setError(reason instanceof Error?reason.message:t('mcp.connectionFailed'));await load()}finally{setBusy(null)}}
  async function toggle(server:McpServer){setBusy(server.id);try{await api(`/mcp-servers/${server.id}/${server.status==='disabled'?'enable':'disable'}`,{method:'POST'});await load()}finally{setBusy(null)}}
  async function remove(server:McpServer){try{await api(`/mcp-servers/${server.id}`,{method:'DELETE'});await load();toast(t('mcp.deleted',{name:server.name}),'success',{kind:'mcp.server.deleted',resource_type:'mcp_server',resource_id:server.id})}catch(reason){setError(reason instanceof Error?reason.message:t('mcp.deleteFailed'))}}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy('save');setError('');const data=new FormData(event.currentTarget);const name=String(data.get('name'));let command:string[]=[];if(transport==='stdio'){try{const parsed=JSON.parse(String(data.get('command')));if(!Array.isArray(parsed)||!parsed.every(item=>typeof item==='string'))throw new Error();command=parsed}catch{setError(t('mcp.invalidCommand'));setBusy(null);return}}const bearer=String(data.get('bearer')||'');const payload={name,slug:name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),description:data.get('description'),transport,endpoint:transport==='streamable-http'?data.get('endpoint'):null,command,visibility:data.get('visibility'),secret_headers:bearer?{Authorization:`Bearer ${bearer}`}:{},secret_environment:{}};try{const server=await api<McpServer>('/mcp-servers',{method:'POST',body:JSON.stringify(payload)});setCreating(false);await load();if(transport==='streamable-http')await connect(server);else toast(t('mcp.stdioSaved'),'success')}catch(reason){setError(reason instanceof Error?reason.message:t('mcp.saveFailed'))}finally{setBusy(null)}}
  return <div className="page"><header className="page-header"><div><p className="eyebrow">{t('mcp.eyebrow',{count:servers.length.toString().padStart(2,'0')})}</p><h1>{t('mcp.title')}</h1><p>{t('mcp.description')}</p></div><button className="button primary" onClick={()=>{setCreating(true);setError('')}}><Plus size={16}/>{t('mcp.add')}</button></header>
    {error&&<div className="form-error page-error">{error}</div>}
    <div className="provider-list">{servers.map(server=><article className="provider-card" key={server.id}><div className="provider-mark"><PlugZap/></div><div className="provider-main"><p className="eyebrow">{server.transport}</p><h2>{server.name}</h2><code>{server.endpoint??server.command.join(' ')}</code><div className="provider-flags"><span><i className={`status-dot ${server.status==='error'?'failed':server.status}`}/>{translateStatus(server.status)}</span><span>{t('mcp.tools',{count:server.tools_snapshot.length})}</span>{server.has_secret&&<span><KeyRound size={12}/>{t('mcp.secretSaved')}</span>}</div><small>{server.status_message}</small></div><div className="provider-actions">{server.transport==='streamable-http'&&server.status!=='disabled'&&<button className="button ghost" disabled={busy===server.id} onClick={()=>connect(server)}>{busy===server.id?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>} {t('common.actions.connect')}</button>}<button className="icon-button" title={server.status==='disabled'?t('common.actions.enable'):t('common.actions.disable')} onClick={()=>toggle(server)}>{server.status==='disabled'?<Power size={14}/>:<Ban size={14}/>}</button><button className="icon-button danger" title={t('common.actions.delete')} onClick={()=>remove(server)}><Trash2 size={14}/></button></div>{!!server.tools_snapshot.length&&<div className="model-list"><p className="eyebrow">{t('mcp.discoveredTools')}</p>{server.tools_snapshot.map(tool=><span key={tool.name} title={tool.description}>{tool.title??tool.name}</span>)}</div>}</article>)}{!servers.length&&<div className="empty-state provider-empty"><Server size={25}/><h3>{t('mcp.emptyTitle')}</h3><p>{t('mcp.emptyDescription')}</p></div>}</div>
    {creating&&<div className="modal-backdrop" onMouseDown={()=>setCreating(false)}><form className="modal provider-modal" onSubmit={save} onMouseDown={event=>event.stopPropagation()}><p className="eyebrow">{t('mcp.newEyebrow')}</p><h2>{t('mcp.connectTitle')}</h2><div className="provider-kind"><button type="button" className={transport==='streamable-http'?'active':''} onClick={()=>setTransport('streamable-http')}><strong>Streamable HTTP</strong><small>{t('mcp.remoteEndpoint')}</small></button><button type="button" className={transport==='stdio'?'active':''} onClick={()=>setTransport('stdio')}><strong>stdio</strong><small>{t('mcp.workerProcess')}</small></button></div><div className="form-grid"><label>{t('common.fields.name')}<input name="name" required placeholder="Filesystem MCP"/></label><label>{t('common.fields.visibility')}<select name="visibility"><option value="private">{translateVisibility('private')}</option><option value="public">{translateVisibility('public')}</option><option value="groups">{translateVisibility('groups')}</option></select></label><label className="span-2">{t('common.fields.description')}<input name="description" placeholder={t('mcp.descriptionPlaceholder')}/></label>{transport==='streamable-http'?<><label className="span-2">{t('mcp.endpoint')}<input name="endpoint" required defaultValue="http://host.containers.internal:3000/mcp"/></label><label className="span-2">{t('mcp.bearerOptional')}<input type="password" name="bearer" autoComplete="off"/></label></>:<label className="span-2">{t('mcp.command')}<textarea className="code-input" name="command" required defaultValue={'["npx","-y","@modelcontextprotocol/server-filesystem","/workspace"]'}/></label>}</div>{transport==='streamable-http'?<div className="connection-hint"><CheckCircle2 size={14}/><p>{t('mcp.httpHint')}</p></div>:<div className="connection-hint"><Play size={14}/><p>{t('mcp.stdioHint')}</p></div>}{error&&<div className="connection-result failed"><XCircle size={17}/><p>{error}</p></div>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setCreating(false)}>{t('common.actions.cancel')}</button><button className="button primary" disabled={busy==='save'}>{t('common.actions.saveAndConnect')}</button></div></form></div>}
  </div>
}
