import { FormEvent, useEffect, useState } from 'react'
import { Ban, CheckCircle2, KeyRound, LoaderCircle, Play, PlugZap, Plus, Power, RefreshCw, Server, Trash2, XCircle } from 'lucide-react'
import { api } from '../lib/api'
import { toast } from '../lib/toast'
import type { McpServer } from '../types'

type Connection = {ok:boolean;message:string;protocol_version?:string;tools:Array<Record<string,unknown>>}

export function McpServersPage(){
  const [servers,setServers]=useState<McpServer[]>([])
  const [creating,setCreating]=useState(false)
  const [transport,setTransport]=useState<'streamable-http'|'stdio'>('streamable-http')
  const [busy,setBusy]=useState<string|null>(null)
  const [error,setError]=useState('')
  const load=()=>api<McpServer[]>('/mcp-servers').then(setServers)
  useEffect(()=>{load().catch(()=>undefined);const timer=window.setInterval(()=>load().catch(()=>undefined),5000);return()=>window.clearInterval(timer)},[])
  async function connect(server:McpServer){setBusy(server.id);setError('');try{const result=await api<Connection>(`/mcp-servers/${server.id}/connect`,{method:'POST'});toast(`${server.name}: ${result.tools.length} MCP tools synchronizovaných.`,'success',{kind:'mcp.server.connected',resource_type:'mcp_server',resource_id:server.id});await load()}catch(reason){setError(reason instanceof Error?reason.message:'MCP spojenie zlyhalo');await load()}finally{setBusy(null)}}
  async function toggle(server:McpServer){setBusy(server.id);try{await api(`/mcp-servers/${server.id}/${server.status==='disabled'?'enable':'disable'}`,{method:'POST'});await load()}finally{setBusy(null)}}
  async function remove(server:McpServer){try{await api(`/mcp-servers/${server.id}`,{method:'DELETE'});await load();toast(`MCP server „${server.name}“ bol vymazaný.`,'success',{kind:'mcp.server.deleted',resource_type:'mcp_server',resource_id:server.id})}catch(reason){setError(reason instanceof Error?reason.message:'MCP server sa nepodarilo vymazať')}}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy('save');setError('');const data=new FormData(event.currentTarget);const name=String(data.get('name'));let command:string[]=[];if(transport==='stdio'){try{const parsed=JSON.parse(String(data.get('command')));if(!Array.isArray(parsed)||!parsed.every(item=>typeof item==='string'))throw new Error();command=parsed}catch{setError('Príkaz musí byť JSON pole argumentov, napr. ["npx","-y","server"]');setBusy(null);return}}const bearer=String(data.get('bearer')||'');const payload={name,slug:name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),description:data.get('description'),transport,endpoint:transport==='streamable-http'?data.get('endpoint'):null,command,visibility:data.get('visibility'),secret_headers:bearer?{Authorization:`Bearer ${bearer}`}:{},secret_environment:{}};try{const server=await api<McpServer>('/mcp-servers',{method:'POST',body:JSON.stringify(payload)});setCreating(false);await load();if(transport==='streamable-http')await connect(server);else toast('stdio MCP server bol uložený. Overí ho prvý MCP job na workerovi.','success')}catch(reason){setError(reason instanceof Error?reason.message:'MCP server sa nepodarilo uložiť')}finally{setBusy(null)}}
  return <div className="page"><header className="page-header"><div><p className="eyebrow">MCP SERVER REGISTRY / {servers.length.toString().padStart(2,'0')}</p><h1>MCP servery</h1><p>Registrované nástroje pre deterministických MCP agentov a pipeline.</p></div><button className="button primary" onClick={()=>{setCreating(true);setError('')}}><Plus size={16}/>Pridať MCP server</button></header>
    {error&&<div className="form-error page-error">{error}</div>}
    <div className="provider-list">{servers.map(server=><article className="provider-card" key={server.id}><div className="provider-mark"><PlugZap/></div><div className="provider-main"><p className="eyebrow">{server.transport}</p><h2>{server.name}</h2><code>{server.endpoint??server.command.join(' ')}</code><div className="provider-flags"><span><i className={`status-dot ${server.status==='error'?'failed':server.status}`}/>{server.status.toUpperCase()}</span><span>{server.tools_snapshot.length} tools</span>{server.has_secret&&<span><KeyRound size={12}/>Secret uložený</span>}</div><small>{server.status_message}</small></div><div className="provider-actions">{server.transport==='streamable-http'&&server.status!=='disabled'&&<button className="button ghost" disabled={busy===server.id} onClick={()=>connect(server)}>{busy===server.id?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>}Connect & sync</button>}<button className="icon-button" title={server.status==='disabled'?'Povoliť':'Zakázať'} onClick={()=>toggle(server)}>{server.status==='disabled'?<Power size={14}/>:<Ban size={14}/>}</button><button className="icon-button danger" title="Vymazať" onClick={()=>remove(server)}><Trash2 size={14}/></button></div>{!!server.tools_snapshot.length&&<div className="model-list"><p className="eyebrow">DISCOVERED TOOLS</p>{server.tools_snapshot.map(tool=><span key={tool.name} title={tool.description}>{tool.title??tool.name}</span>)}</div>}</article>)}{!servers.length&&<div className="empty-state provider-empty"><Server size={25}/><h3>Žiadny MCP server</h3><p>Pripoj Streamable HTTP endpoint alebo zaregistruj stdio príkaz pre worker.</p></div>}</div>
    {creating&&<div className="modal-backdrop" onMouseDown={()=>setCreating(false)}><form className="modal provider-modal" onSubmit={save} onMouseDown={event=>event.stopPropagation()}><p className="eyebrow">NEW MCP SERVER</p><h2>Pripojiť MCP server</h2><div className="provider-kind"><button type="button" className={transport==='streamable-http'?'active':''} onClick={()=>setTransport('streamable-http')}><strong>Streamable HTTP</strong><small>Vzdialený endpoint</small></button><button type="button" className={transport==='stdio'?'active':''} onClick={()=>setTransport('stdio')}><strong>stdio</strong><small>Proces na workerovi</small></button></div><div className="form-grid"><label>Názov<input name="name" required placeholder="Filesystem MCP"/></label><label>Viditeľnosť<select name="visibility"><option value="private">Private</option><option value="public">Public</option><option value="groups">Groups</option></select></label><label className="span-2">Popis<input name="description" placeholder="Aké nástroje server poskytuje"/></label>{transport==='streamable-http'?<><label className="span-2">MCP endpoint<input name="endpoint" required defaultValue="http://host.containers.internal:3000/mcp"/></label><label className="span-2">Bearer token (nepovinný)<input type="password" name="bearer" autoComplete="off"/></label></>:<label className="span-2">Príkaz ako JSON argumenty<textarea className="code-input" name="command" required defaultValue={'["npx","-y","@modelcontextprotocol/server-filesystem","/workspace"]'}/></label>}</div>{transport==='streamable-http'?<div className="connection-hint"><CheckCircle2 size={14}/><p>Po uložení sa vykoná MCP initialize a načíta sa reálny zoznam tools.</p></div>:<div className="connection-hint"><Play size={14}/><p>Príkaz sa nespúšťa cez shell. Dostupnosť overí worker pri prvom MCP jobe.</p></div>}{error&&<div className="connection-result failed"><XCircle size={17}/><p>{error}</p></div>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setCreating(false)}>Zrušiť</button><button className="button primary" disabled={busy==='save'}>Uložiť a pripojiť</button></div></form></div>}
  </div>
}
